In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from cpt.solver import make_env
from cpt.solver.iter_nn import Solver

In [3]:
env = make_env()
env.reset()
import torch
actor_before = torch.load('../../model/pred_xyz/best_actor')

solver = Solver.parse(env, low_steps=40, parse_prefix='solver', head_cfg=dict(TYPE="ParticleHead"))
solver.actor.load_state_dict(actor_before.state_dict())

E: 5000.0
gravity: (0., -1., 0.)
grid_size: (1., 1., 1.)
ground_friction: 5.0
max_steps: 1024
n_particles: 20000
nu: 0.2
yield_stress: 100.0
LOADING....
Loaded with 0.00028443336486816406 secs.
GPU 0/1 memory: free=4.873, total=10.917
init renderer


<All keys matched successfully>

In [4]:
inp = []
for i in range(10):
    inp.append(env.reset())


In [5]:
data = solver.actor(inp)

means tensor([-0.7847,  0.5581, -0.8101, -1.4464,  0.2182,  0.3797,  0.7803,  0.5909,
         0.2043,  1.2877,  1.2117, -0.2895], device='cuda:0',
       grad_fn=<SelectBackward0>)
rts tensor([-8.3696e-01,  1.4316e+00,  4.0467e+00,  8.3259e-02,  6.5191e-02,
        -8.8027e-03, -3.0749e+01,  3.9533e+01,  4.8577e+01,  2.6242e-01,
        -9.9332e-02, -4.4524e-01], device='cuda:0')


In [7]:
inp[0]['agent']
import torch
action = torch.rand(size=(10, 12), device='cuda:0')
solver.actor.head.bc_loss(inp, data, action)

tensor([1.0000, 1.0000, 1.0000, 0.9997, 0.9999, 0.9999], device='cuda:0') actions tensor([1., 1., 1., 1., 1., 1.], device='cuda:0')
tensor([-0.8370,  1.4316,  4.0467,  0.0833,  0.0652, -0.0088], device='cuda:0',
       grad_fn=<DivBackward0>) actions tensor([1., 1., 1., 1., 1., 1.], device='cuda:0')
tensor([1.0000, 1.0000, 1.0000, 0.9998, 0.9996, 0.9995], device='cuda:0') actions tensor([1., 1., 1., 1., 1., 1.], device='cuda:0')
tensor([-30.7487,  39.5334,  48.5767,   0.2624,  -0.0993,  -0.4452],
       device='cuda:0', grad_fn=<DivBackward0>) actions tensor([1., 1., 1., 1., 1., 1.], device='cuda:0')


{'mean_loss': tensor(401.3214, device='cuda:0', grad_fn=<MseLossBackward0>),
 'p_loss': tensor(15.9340, device='cuda:0', grad_fn=<AddBackward0>)}